export const salesTeam = [
  {
    name: "João Silva",
    sales: 45000,
    target: 40000,
    percentage: 112,
    status: "Superou",
    photo: "/placeholder.svg?height=60&width=60",
  },
  {
    name: "Maria Santos",
    sales: 42000,
    target: 40000,
    percentage: 105,
    status: "Superou",
    photo: "/placeholder.svg?height=60&width=60",
  },
  {
    name: "Pedro Costa",
    sales: 38000,
    target: 40000,
    percentage: 95,
    status: "Próximo",
    photo: "/placeholder.svg?height=60&width=60",
  },
  {
    name: "Ana Oliveira",
    sales: 35000,
    target: 40000,
    percentage: 87,
    status: "Próximo",
    photo: "/placeholder.svg?height=60&width=60",
  },
  {
    name: "Carlos Mendes",
    sales: 32000,
    target: 40000,
    percentage: 80,
    status: "Abaixo",
    photo: "/placeholder.svg?height=60&width=60",
  },
  {
    name: "Lucia Ferreira",
    sales: 28000,
    target: 40000,
    percentage: 70,
    status: "Abaixo",
    photo: "/placeholder.svg?height=60&width=60",
  },
  {
    name: "Fernando Silva",
    sales: 26500,
    target: 40000,
    percentage: 66,
    status: "Abaixo",
    photo: "/placeholder.svg?height=60&width=60",
  },
  {
    name: "Juliana Costa",
    sales: 25000,
    target: 40000,
    percentage: 62,
    status: "Abaixo",
    photo: "/placeholder.svg?height=60&width=60",
  },
  {
    name: "Ricardo Santos",
    sales: 23500,
    target: 40000,
    percentage: 59,
    status: "Abaixo",
    photo: "/placeholder.svg?height=60&width=60",
  },
  {
    name: "Camila Rodrigues",
    sales: 22000,
    target: 40000,
    percentage: 55,
    status: "Abaixo",
    photo: "/placeholder.svg?height=60&width=60",
  },
]

export const generateDashboardData = () => ({
  metrics: [
    { type: "sales", title: "Vendas", value: "R$ 100.000", trend: 5, target: "R$ 90.000", percentage: 111 },
    { type: "leads", title: "Leads", value: "1.200", trend: 2, target: "1.000", percentage: 120 },
    { type: "followers", title: "Seguidores", value: "8.000", trend: 1 },
    { type: "conversion", title: "Conversão", value: "12%", trend: -1 },
  ],
  salesData: [
    { day: "01/06", sales: 3000, target: 2500 },
    { day: "02/06", sales: 3200, target: 2500 },
    { day: "03/06", sales: 2800, target: 2500 },
    { day: "04/06", sales: 3500, target: 2500 },
    { day: "05/06", sales: 4000, target: 2500 },
  ],
  marketingData: [
    { channel: "Instagram", leads: 400 },
    { channel: "Facebook", leads: 300 },
    { channel: "Google Ads", leads: 250 },
    { channel: "LinkedIn", leads: 150 },
  ],
  salesFunnel: [
    { stage: "Prospecção", count: 120 },
    { stage: "Contato", count: 80 },
    { stage: "Proposta", count: 40 },
    { stage: "Fechamento", count: 20 },
  ],
  salesTeam,
  campaigns: [
    { name: "Campanha A", roi: 120, spent: 1000, conversions: 50 },
    { name: "Campanha B", roi: 90, spent: 800, conversions: 30 },
  ],
  // Os campos opcionais podem ser adicionados conforme necessidade dos outros componentes
})
